const cfg = window.SALON_CONFIG;
const $ = id => document.getElementById(id);
function fillBooking(){ $('petType').innerHTML=cfg.petTypes.map(x=>`<option>${x}</option>`).join(''); $('service').innerHTML=cfg.services.map(x=>`<option>${x}</option>`).join(''); const d=new Date(); d.setDate(d.getDate()+1); $('date').min=d.toISOString().slice(0,10); }
function openBooking(){ $('bookingModal').classList.add('open'); $('bookingModal').setAttribute('aria-hidden','false'); fillBooking(); document.body.style.overflow='hidden'; }
function closeBooking(){ $('bookingModal').classList.remove('open'); $('bookingModal').setAttribute('aria-hidden','true'); document.body.style.overflow=''; }
$('bookingModal').addEventListener('click',e=>{if(e.target.id==='bookingModal')closeBooking();});
function buildMessage(){ const date=new Date($('date').value+'T12:00:00'); const dateText=date.toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}); return `Здравствуйте! Хочу записаться в груминг-салон.\n\n🐾 Питомец: ${$('petType').value}\n🐶 Порода: ${$('breed').value}\n✂️ Услуга: ${$('service').value}\n📅 Желаемая дата: ${dateText}\n🕐 Пожелания по времени: ${$('comment').value || 'не указаны'}\n👤 Имя: ${$('clientName').value}\n📞 Телефон: ${$('phone').value || 'не указан'}\n\nПодскажите, пожалуйста, какое время будет свободно?`; }
async function copyText(text){ try{await navigator.clipboard.writeText(text);return true;}catch{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();let ok=false;try{ok=document.execCommand('copy')}catch{}area.remove();return ok;}}
$('bookingForm').addEventListener('submit',async e=>{e.preventDefault();const message=buildMessage();const copied=await copyText(message);const payload={petType:$('petType').value,breed:$('breed').value,service:$('service').value,date:$('date').value,comment:$('comment').value,clientName:$('clientName').value,phone:$('phone').value,message};try{await fetch('/api/booking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),keepalive:true});}catch{} $('copyStatus').textContent=copied?'Готово: текст заявки скопирован. Сейчас откроются сообщения сообщества VK — вставьте текст (⌘V) и отправьте.':'VK открывается. Скопируйте готовый текст из поля заявки вручную, если буфер обмена недоступен.'; setTimeout(()=>{window.location.href=cfg.vkMessagesUrl;},650);});
const reviews=[['review_01.png','Инкогнито 0446'],['review_02.png','Наталья Никифорова'],['review_03.png','Надежда Терехина'],['review_04.png','Оксана Ш.'],['review_05.png','233336 Сахарова'],['review_06.png','Алексей Могилёв'],['review_07.png','Светлана Савельева'],['review_08.png','Юлия Курилова']]; $('reviewGrid').innerHTML=reviews.map(([file,name])=>`<article class="review-card"><img loading="lazy" src="assets/reviews/${file}" alt="Отзыв клиента ${name}"><div class="stars">★★★★★</div><div class="review-name">${name}</div></article>`).join('');
const gallery=[['work_01.jpeg','Питомец после ухода'],['work_02.jpeg','Стрижка и уход'],['work_03.jpeg','Атмосфера салона'],['work_04.jpeg','Зона ожидания'],['work_05.jpeg','Профессиональная косметика'],['work_06.jpeg','Питомец после груминга'],['work_07.jpeg','Результат работы'],['work_08.jpeg','Груминг — результат'],['work_09.jpeg','Питомец после ухода'],['work_10.jpeg','Работа мастера'],['work_11.jpeg','Стрижка — до и после'],['work_12.jpeg','Стрижка — до и после'],['work_13.jpeg','Ухоженный питомец'],['work_14.jpeg','Работа мастера'],['work_15.jpeg','Стрижка — до и после'],['work_16.jpeg','Стрижка и укладка'],['work_17.jpeg','Пудель после ухода']]; $('galleryGrid').innerHTML=gallery.filter(([src])=>{return true}).map(([src,alt],i)=>`<figure class="work-card ${i===0?'featured':''}"><img loading="lazy" src="assets/gallery/${src}" alt="${alt}"><figcaption>${alt}</figcaption></figure>`).join('');
$('videoGrid').innerHTML='<article class="video-card"><video controls preload="metadata" playsinline src="assets/video/pet_video.mp4"></video><h3>Пёсель кайфует после ухода 🐶</h3><p>Небольшой фрагмент с питомцем — спокойным, ухоженным и довольным после процедуры.</p></article>';
